return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	dependencies = { { "nvim-tree/nvim-web-devicons" } },
	config = function()
		require("dashboard").setup({
			theme = "doom",
			config = {
				header = {
					"",
					"",
					"",
					"",
					"",
					"",
					"	███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗",
					"	████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║",
					"	██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║",
					"	██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║",
					"	██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║",
					"	╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝",
					"",
					"",
					"",
					"",
					"",
					"",
				},
				center = {
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Open Project",
						desc_hl = "String",
						action = "Telescope neovim-project discover",
						key = "o",
						key_hl = "Number",
						key_format = " %s",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Recent Porjects",
						desc_hl = "String",
						action = "Telescope neovim-project history",
						key = "O",
						key_hl = "Number",
						key_format = " %s",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Find File",
						desc_hl = "String",
						action = "Telescope find_files",
						key = "f",
						key_hl = "Number",
						key_format = " %s",
					},
					{
						icon = "󰗍 ",
						icon_hl = "Title",
						desc = "Recent Files",
						desc_hl = "String",
						action = "Telescope oldfiles",
						key = "r",
						key_hl = "Number",
						key_format = " %s",
					},
					{
						icon = " ",
						icon_hl = "Title",
						desc = "Config Folder",
						desc_hl = "String",
						action = "edit ~/.config/nvim",
						key = "c",
						key_hl = "Number",
						key_format = " %s",
					},
					{
						icon = "󰿅 ",
						icon_hl = "Title",
						desc = "Quit",
						desc_hl = "String",
						action = "quit",
						key = "q",
						key_hl = "Number",
						key_format = " %s",
					},
				},
				footer = {},
			},
		})
	end,
}
